sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-thread-dev libboost-system-dev libboost-test-dev

language: cpp

compiler:
  - gcc

script:
  - make
  - make test